### ISSUE TITLE
Doesn't work with computer accounts

### ISSUE THREAD

**Issue by tallmega** [tallmega/AD2CIDRs#1]
Collecting and resolving AD computers using the following inputs:
Domain Controller: test.ca
Domain: test.ca
Username: test$@test.ca
Traceback (most recent call last):
  File "/home/kali/AD2CIDRs.py", line 122, in <module>
    main()
  File "/home/kali/AD2CIDRs.py", line 115, in main
    computer_names = get_computers(domain_controller, domain, username, password)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/AD2CIDRs.py", line 43, in get_computers
    conn = Connection(server, user=username, password=password, auto_bind=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 363, in __init__
    self._do_auto_bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 412, in _do_auto_bind
    raise LDAPBindError(error)
ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials

**Comment by tallmega** [comment]
Fixed with NTLM authentication and  better input parameter handling.

#https://github.com/tallmega/AD2CIDRs/commit/30ecddef578ee4b5c2cef18735c767375929fb55
